import { Configuration, OpenAIApi } from "openai";
import * as dotenv from "dotenv"
dotenv.config()

const configuration = new Configuration({
    apiKey: process.env.SUMMARY_ASSIST,
});
const openai = new OpenAIApi(configuration)

const AiContentDetector = async (req,res)=>{
    
        let text
        if (req.body.url) {
            // Fetch the text from the URL  
            text = req.body.url
        } else {
            // Use the text provided in the request
            text = req.body.text
    
        }

        if(!text){
            res.status(400).send({ error: "Kindly provide the content to analyze." });
            return
        }
    
        try {
            const response = await openai.createCompletion({
                model: "text-davinci-003",
                prompt: `Is the following text generated by AI? ${text} Please provide a 'Yes' or 'No' response, along with any relevant contextual information if necessary." `,
                temperature: 1,
                max_tokens: 15,
                top_p: 1,
                frequency_penalty: 0.5,
                presence_penalty: 0,
            });
    
            const isAiGenerated = response.data.choices[0].text;
    
            res.status(200).send({ isAiGenerated });
        } catch (error) {
            res.status(500).send({ error: "OpenAI API Error" });
        }
    }

export {AiContentDetector}